### ISSUE TITLE
Does kubeprober support  k8s 1.14 ?

### ISSUE THREAD

**Issue by ChanKunggc** [erda-project/kubeprober#122]
#### What would you like to be added:
Does kubeprober support  k8s 1.14 ? In k8s 1.14,we don't have  'v1' version.

**Comment by sixther-dc** [comment]
需要hack一下，试一下这个：

`sed -i 's/jsonPath/JSONPath/g' deployment/probe-agent.yaml 
sed -i 's#apiextensions.k8s.io/v1#apiextensions.k8s.io/v1beta1#g' deployment/probe-agent.yaml 
sed -i '/x-kubernetes-list-map-key/,+3d' deployment/probe-agent.yaml`

**Comment by sixther-dc** [comment]
> #### What would you like to be added:
> Does kubeprober support k8s 1.14 ? In k8s 1.14,we don't have 'v1' version.

需要hack一下，试一下这个

sed -i 's/jsonPath/JSONPath/g' deployment/probe-agent.yaml
sed -i 's#apiextensions.k8s.io/v1#apiextensions.k8s.io/v1beta1#g' deployment/probe-agent.yaml
sed -i '/x-kubernetes-list-map-key/,+3d' deployment/probe-agent.yaml

**Comment by ChanKunggc** [comment]
> > #### What would you like to be added:
> > Does kubeprober support k8s 1.14 ? In k8s 1.14,we don't have 'v1' version.
> 
> 需要hack一下，试一下这个
> 
> sed -i 's/jsonPath/JSONPath/g' deployment/probe-agent.yaml sed -i 's#apiextensions.k8s.io/v1#apiextensions.k8s.io/v1beta1#g' deployment/probe-agent.yaml sed -i '/x-kubernetes-list-map-key/,+3d' deployment/probe-agent.yaml

我用controller-gen重新生成了下v1beta1的yaml,应该没什么问题.
