### ISSUE TITLE
standalone案例无法正确运行

### ISSUE THREAD

**Issue by dotDuck** [erda-project/kubeprober#125]
#### What happened: 
standalone案例无法正确运行，现象：

1. probe-agent启动报错找不到configmap-probeagent
2. probe-agent日志报错各类资源list等权限forbidden
3. Prober 示例运行job提示无法找到configmap-extra-config

#### What you expected to happen: 
standalone案例正确运行

#### How to reproduce it (as minimally and precisely as possible): 

1. 按照文档 https://docs.erda.cloud/1.5/manual/eco-tools/kubeprober/best-practices/standalone_kubeprober.html 进行操作，prober-agent容器无法正常启动；
2. 按照文档 https://docs.erda.cloud/1.5/manual/eco-tools/kubeprober/guides/first_prober.html 运行prober示例无法正确运行job

#### Anything else we need to know?:
已自行定位问题原因并修改：
https://github.com/dotDuck/kubeprober/commit/ade3b0de37bf1ce586cc542e7dcbbfee1ef0d8c1#diff-ebef744877d88253a7e2a26f413155959097fe3659045131b32418fb9af80937
如果可以的话可以进行pull-request。

问题1原因：`probe-agent-standalone.yaml`声明问题

- 缺少configmap`probeagent`的声明（对应现象1）
- serviceaccount`kubeprober-worker`声明后未使用，应该将kubeprober-worker-rolebinding绑定的serviceacccount更换为`kubeprober`（对应现象2）
- probe-agent镜像更新到docker-hub中最新版（也可忽略）
- 仍有其他configmap找不到的日志报错，但是不影响整体运行，如：dice-cluster-info、dice-tools-info、dice-addon-info

问题2原因：`prober-demo-example`声明问题

- 缺少configmap`extra-config`的声明，但是配置内容无从参考，也找不到合适的新增位置，临时新建cm解决（对应现象3）

#### Environment:
- Erda version: 无
- Kubernetes version (use `kubectl version`): Kind kubernetes v1.19.11

**Comment by dotDuck** [comment]
@WeiXuSeu

**Comment by jferic** [comment]
pr is welcome～

**Comment by jferic** [comment]
> #### What happened:
> standalone案例无法正确运行，现象：
> 
> 1. probe-agent启动报错找不到configmap-probeagent
> 2. probe-agent日志报错各类资源list等权限forbidden
> 3. Prober 示例运行job提示无法找到configmap-extra-config
> 
> #### What you expected to happen:
> standalone案例正确运行
> 
> #### How to reproduce it (as minimally and precisely as possible):
> 1. 按照文档 https://docs.erda.cloud/1.5/manual/eco-tools/kubeprober/best-practices/standalone_kubeprober.html 进行操作，prober-agent容器无法正常启动；
> 2. 按照文档 https://docs.erda.cloud/1.5/manual/eco-tools/kubeprober/guides/first_prober.html 运行prober示例无法正确运行job
> 
> #### Anything else we need to know?:
> 已自行定位问题原因并修改： [dotDuck@ade3b0d#diff-ebef744877d88253a7e2a26f413155959097fe3659045131b32418fb9af80937](https://github.com/dotDuck/kubeprober/commit/ade3b0de37bf1ce586cc542e7dcbbfee1ef0d8c1#diff-ebef744877d88253a7e2a26f413155959097fe3659045131b32418fb9af80937) 如果可以的话可以进行pull-request。
> 
> 问题1原因：`probe-agent-standalone.yaml`声明问题
> 
> * 缺少configmap`probeagent`的声明（对应现象1）
> * serviceaccount`kubeprober-worker`声明后未使用，应该将kubeprober-worker-rolebinding绑定的serviceacccount更换为`kubeprober`（对应现象2）
> * probe-agent镜像更新到docker-hub中最新版（也可忽略）
> * 仍有其他configmap找不到的日志报错，但是不影响整体运行，如：dice-cluster-info、dice-tools-info、dice-addon-info
> 
> 问题2原因：`prober-demo-example`声明问题
> 
> * 缺少configmap`extra-config`的声明，但是配置内容无从参考，也找不到合适的新增位置，临时新建cm解决（对应现象3）
> 
> #### Environment:
> * Erda version: 无
> * Kubernetes version (use `kubectl version`): Kind kubernetes v1.19.11

pr is welcome~
