### ISSUE TITLE
诊断结果如何实现可视化操作

### ISSUE THREAD

**Issue by wxuedong** [erda-project/kubeprober#141]
关于诊断的结果实现可视化没有在项目的相关文档中体现出来，

以及如何对接到prometheus 配置以及暴露的metrics 都有哪些文档中没有相关的描述 ，是否可以完善文档或者补全相关可视化操作或功能，谢谢。

**Comment by yanhongchang** [comment]
@wxuedong 怎么没有回复就关闭了issue？
