### ISSUE TITLE
reconciler group": "kubeprober.erda.cloud", "reconciler kind": "Probe", "name": "probe-test01", "namespace": "kubeprober", "error": "Job.batch \"probe-test01\" is invalid: [spec.template.spec.containers: Required value, spec.template.spec.restartPolicy: Unsupported value: \"Always\": supported values: \"OnFailure\", \"Never\"]"

### ISSUE THREAD

**Issue by LeoWenxiang** [erda-project/kubeprober#60]
probe yaml 

apiVersion: kubeprober.erda.cloud/v1
kind: Probe
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeprober.erda.cloud/v1","kind":"Probe","metadata":{"annotations":{},"name":"probe-test01","namespace":"kubeprober"},"spec":{"probeList":[{"name":"probe-test01","spec":{"containers":[{"image":"kubeprober/demo-error:v0.0.1","name":"demo-error","resources":{"requests":{"cpu":"10m","memory":"50Mi"}}}],"restartPolicy":"Never"}}]}}
  creationTimestamp: "2021-08-18T09:24:26Z"
  generation: 1
  name: probe-test01
  namespace: kubeprober
  resourceVersion: "1255475"
  selfLink: /apis/kubeprober.erda.cloud/v1/namespaces/kubeprober/probes/probe-test01
  uid: 1c6a2f23-a68c-4283-9869-0c2ed3e891c7
spec:
  policy: {}
  probeList:
  - name: probe-test01
    spec:
      containers:
      - image: kubeprober/demo-error:v0.0.1
        name: demo-error
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
      restartPolicy: Never
status:
  md5: 0e69f266c6e6d360c7e4130a4b4e6ff4

probe-agent error
![image](https://user-images.githubusercontent.com/16400533/129873936-36bde682-1608-4788-9946-6b7497d5ba8e.png)

**Comment by sixther-dc** [comment]
This is a bug, we will release a new version this week to fix this problem，
Thanks for letting us know it。

**Comment by WeiXuSeu** [comment]
Job is only appropriate for pods with RestartPolicy equal to OnFailure or Never. (Note: If RestartPolicy is not set, the default value is Always.)
So we must set the RestartPolicy explicitly now, and we will optimize this by set the default restart policy to `Never`.
 
pr: [job restart policy bugfix](https://github.com/erda-project/kubeprober/pull/63)
```
spec:
  template:
    containers:
      - name: demo-error-test
        image: kubeprober/demo-error:v0.0.1
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    restartPolicy: Never
```

**Comment by sixther-dc** [comment]
this question have fixed in new version。 

https://github.com/erda-project/kubeprober/releases/tag/v0.1.0
